name: Sheduling of task 
on: 
  schedule:
    - cron: '*/5 * * * *'
jobs:
  schedule:
    runs-on: ubuntu-latest
    steps:
    - name: Info
      run: |
        echo "This the first time im using actions"
