name: manual trigger
on: 
  issues:
    types:
      -  opened
jobs:
  manual:
    runs-on: ubuntu-latest
    steps:
    - name: Info
      run: |
        echo "This the second time im using actions"
