name: testing
on: 
  push:
  workflow_dispatch:
env:
  cloud: AWS
jobs:
  welcome:
    runs-on: ubuntu-latest
    env:
      greeting: welcome to
    steps:
      - name: prinitng
        run: echo $greeting $cloud $name
        env:
          name: pranav
            
    
        
