name: Using secrets
on:
  workflow_dispatch
env:
  ACTIONS_STEP_DEBUG: true
jobs:
  secrets:
   runs-on: ubuntu-latest
   steps:
     - name: using secrets
       run: |
         echo " secret value = ${{ secrets.MY_KEY }}"
